courses = [];
course1 = prompt("Course One", "Math");
courses.push(course1);
course2 = prompt("Course Two", "Bio");
courses.push(course2);
course3 = prompt("Course Three", "Physics");
courses.push(course3);
course4 = prompt("Course four", "Chemistry");
courses.push(course4);
course5 = prompt("Course Five", "Urdu");
courses.push(course5);
console.log("Your Selected Courses");
console.log(courses);
window.alert("Before Editing " + courses);
document.write("<h1>Your Selected Courses");
document.write("<h1>" + courses);
course1 = prompt("You can Change Course Now", "Math");
courses.splice(0, 1, course1);
course2 = prompt("You can Change Course Now", "Bio");
courses.splice(1, 2, course2);
course3 = prompt("You can Change Course Now", "Physics");
courses.splice(2, 3, course3);
course4 = prompt("You can Change Course Now", "Chemistry");
courses.splice(3, 4, course4);
course5 = prompt("You can Change Course Now", "Urdu");
courses.splice(4, 5, course5);
console.log("Courses after Editing");
console.log(courses);
window.alert(courses + " 'Courses after Editing'");
document.write("<h1>Courses after Editing");
document.write("<h1>" + courses);